/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Management API
 * Management API, describes admin & user activities in the TDEI system.
 *
 * OpenAPI spec version: v0.1
 * Contact: placeholder_support@transequity.cs.washington.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Response } from '../models';
import { Service } from '../models';
import { ServiceUpdate } from '../models';
/**
 * GTFSFlexServiceApi - axios parameter creator
 * @export
 */
export const GTFSFlexServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a GTFS flex service in the TDEI system.Returns the id for the newly created flex service.
         * @summary Creates a GTFS flex service in the TDEI system
         * @param {Service} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createService: async (body: Service, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createService.');
            }
            const localVarPath = `/api/v1/service`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthorizationToken required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets the GTFS Flex services in the TDEI system .
         * @summary Gets the GTFS Flex services in the TDEI system 
         * @param {string} [tdei_service_id] Search by service Id.
         * @param {string} [searchText] Search by service name.
         * @param {string} [tdei_org_id] Owner organization id.
         * @param {Array<number>} [bbox] A bounding box which specifies the area to be searched. A bounding box is specified by a string providing the lat/lon coordinates of the corners of the bounding box. Coordinate should be specified as west, south, east, north.
         * @param {string} [page_no] Page number to fetch
         * @param {string} [page_size] Total records to fetch.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getService: async (tdei_service_id?: string, searchText?: string, tdei_org_id?: string, bbox?: Array<number>, page_no?: string, page_size?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/service`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthorizationToken required

            if (tdei_service_id !== undefined) {
                localVarQueryParameter['tdei_service_id'] = tdei_service_id;
            }

            if (searchText !== undefined) {
                localVarQueryParameter['searchText'] = searchText;
            }

            if (tdei_org_id !== undefined) {
                localVarQueryParameter['tdei_org_id'] = tdei_org_id;
            }

            if (bbox) {
                localVarQueryParameter['bbox'] = bbox;
            }

            if (page_no !== undefined) {
                localVarQueryParameter['page_no'] = page_no;
            }

            if (page_size !== undefined) {
                localVarQueryParameter['page_size'] = page_size;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Activates/Deactives the service.
         * @summary Activates/Deactives the service.
         * @param {string} orgId Owner organization id.
         * @param {string} serviceId Service Id of the service to be Activated/Deactivated.
         * @param {boolean} status Boolean flag to Activate/Deactivate service.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setServiceStatus: async (orgId: string, serviceId: string, status: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgId' is not null or undefined
            if (orgId === null || orgId === undefined) {
                throw new RequiredError('orgId','Required parameter orgId was null or undefined when calling setServiceStatus.');
            }
            // verify required parameter 'serviceId' is not null or undefined
            if (serviceId === null || serviceId === undefined) {
                throw new RequiredError('serviceId','Required parameter serviceId was null or undefined when calling setServiceStatus.');
            }
            // verify required parameter 'status' is not null or undefined
            if (status === null || status === undefined) {
                throw new RequiredError('status','Required parameter status was null or undefined when calling setServiceStatus.');
            }
            const localVarPath = `/api/v1/service/{orgId}/{serviceId}/active/{status}`
                .replace(`{${"orgId"}}`, encodeURIComponent(String(orgId)))
                .replace(`{${"serviceId"}}`, encodeURIComponent(String(serviceId)))
                .replace(`{${"status"}}`, encodeURIComponent(String(status)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthorizationToken required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates a GTFS flex service in the TDEI system.
         * @summary Updates a GTFS flex service in the TDEI system
         * @param {ServiceUpdate} body 
         * @param {string} orgId Owner organization id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateService: async (body: ServiceUpdate, orgId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateService.');
            }
            // verify required parameter 'orgId' is not null or undefined
            if (orgId === null || orgId === undefined) {
                throw new RequiredError('orgId','Required parameter orgId was null or undefined when calling updateService.');
            }
            const localVarPath = `/api/v1/service/{orgId}`
                .replace(`{${"orgId"}}`, encodeURIComponent(String(orgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthorizationToken required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GTFSFlexServiceApi - functional programming interface
 * @export
 */
export const GTFSFlexServiceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Creates a GTFS flex service in the TDEI system.Returns the id for the newly created flex service.
         * @summary Creates a GTFS flex service in the TDEI system
         * @param {Service} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createService(body: Service, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Response>>> {
            const localVarAxiosArgs = await GTFSFlexServiceApiAxiosParamCreator(configuration).createService(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Gets the GTFS Flex services in the TDEI system .
         * @summary Gets the GTFS Flex services in the TDEI system 
         * @param {string} [tdei_service_id] Search by service Id.
         * @param {string} [searchText] Search by service name.
         * @param {string} [tdei_org_id] Owner organization id.
         * @param {Array<number>} [bbox] A bounding box which specifies the area to be searched. A bounding box is specified by a string providing the lat/lon coordinates of the corners of the bounding box. Coordinate should be specified as west, south, east, north.
         * @param {string} [page_no] Page number to fetch
         * @param {string} [page_size] Total records to fetch.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getService(tdei_service_id?: string, searchText?: string, tdei_org_id?: string, bbox?: Array<number>, page_no?: string, page_size?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Service>>> {
            const localVarAxiosArgs = await GTFSFlexServiceApiAxiosParamCreator(configuration).getService(tdei_service_id, searchText, tdei_org_id, bbox, page_no, page_size, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Activates/Deactives the service.
         * @summary Activates/Deactives the service.
         * @param {string} orgId Owner organization id.
         * @param {string} serviceId Service Id of the service to be Activated/Deactivated.
         * @param {boolean} status Boolean flag to Activate/Deactivate service.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setServiceStatus(orgId: string, serviceId: string, status: boolean, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await GTFSFlexServiceApiAxiosParamCreator(configuration).setServiceStatus(orgId, serviceId, status, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Updates a GTFS flex service in the TDEI system.
         * @summary Updates a GTFS flex service in the TDEI system
         * @param {ServiceUpdate} body 
         * @param {string} orgId Owner organization id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateService(body: ServiceUpdate, orgId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await GTFSFlexServiceApiAxiosParamCreator(configuration).updateService(body, orgId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * GTFSFlexServiceApi - factory interface
 * @export
 */
export const GTFSFlexServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Creates a GTFS flex service in the TDEI system.Returns the id for the newly created flex service.
         * @summary Creates a GTFS flex service in the TDEI system
         * @param {Service} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createService(body: Service, options?: AxiosRequestConfig): Promise<AxiosResponse<Response>> {
            return GTFSFlexServiceApiFp(configuration).createService(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets the GTFS Flex services in the TDEI system .
         * @summary Gets the GTFS Flex services in the TDEI system 
         * @param {string} [tdei_service_id] Search by service Id.
         * @param {string} [searchText] Search by service name.
         * @param {string} [tdei_org_id] Owner organization id.
         * @param {Array<number>} [bbox] A bounding box which specifies the area to be searched. A bounding box is specified by a string providing the lat/lon coordinates of the corners of the bounding box. Coordinate should be specified as west, south, east, north.
         * @param {string} [page_no] Page number to fetch
         * @param {string} [page_size] Total records to fetch.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getService(tdei_service_id?: string, searchText?: string, tdei_org_id?: string, bbox?: Array<number>, page_no?: string, page_size?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Service>> {
            return GTFSFlexServiceApiFp(configuration).getService(tdei_service_id, searchText, tdei_org_id, bbox, page_no, page_size, options).then((request) => request(axios, basePath));
        },
        /**
         * Activates/Deactives the service.
         * @summary Activates/Deactives the service.
         * @param {string} orgId Owner organization id.
         * @param {string} serviceId Service Id of the service to be Activated/Deactivated.
         * @param {boolean} status Boolean flag to Activate/Deactivate service.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setServiceStatus(orgId: string, serviceId: string, status: boolean, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return GTFSFlexServiceApiFp(configuration).setServiceStatus(orgId, serviceId, status, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates a GTFS flex service in the TDEI system.
         * @summary Updates a GTFS flex service in the TDEI system
         * @param {ServiceUpdate} body 
         * @param {string} orgId Owner organization id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateService(body: ServiceUpdate, orgId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return GTFSFlexServiceApiFp(configuration).updateService(body, orgId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GTFSFlexServiceApi - object-oriented interface
 * @export
 * @class GTFSFlexServiceApi
 * @extends {BaseAPI}
 */
export class GTFSFlexServiceApi extends BaseAPI {
    /**
     * Creates a GTFS flex service in the TDEI system.Returns the id for the newly created flex service.
     * @summary Creates a GTFS flex service in the TDEI system
     * @param {Service} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GTFSFlexServiceApi
     */
    public async createService(body: Service, options?: AxiosRequestConfig) : Promise<AxiosResponse<Response>> {
        return GTFSFlexServiceApiFp(this.configuration).createService(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Gets the GTFS Flex services in the TDEI system .
     * @summary Gets the GTFS Flex services in the TDEI system 
     * @param {string} [tdei_service_id] Search by service Id.
     * @param {string} [searchText] Search by service name.
     * @param {string} [tdei_org_id] Owner organization id.
     * @param {Array<number>} [bbox] A bounding box which specifies the area to be searched. A bounding box is specified by a string providing the lat/lon coordinates of the corners of the bounding box. Coordinate should be specified as west, south, east, north.
     * @param {string} [page_no] Page number to fetch
     * @param {string} [page_size] Total records to fetch.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GTFSFlexServiceApi
     */
    public async getService(tdei_service_id?: string, searchText?: string, tdei_org_id?: string, bbox?: Array<number>, page_no?: string, page_size?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Service>> {
        return GTFSFlexServiceApiFp(this.configuration).getService(tdei_service_id, searchText, tdei_org_id, bbox, page_no, page_size, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Activates/Deactives the service.
     * @summary Activates/Deactives the service.
     * @param {string} orgId Owner organization id.
     * @param {string} serviceId Service Id of the service to be Activated/Deactivated.
     * @param {boolean} status Boolean flag to Activate/Deactivate service.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GTFSFlexServiceApi
     */
    public async setServiceStatus(orgId: string, serviceId: string, status: boolean, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return GTFSFlexServiceApiFp(this.configuration).setServiceStatus(orgId, serviceId, status, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Updates a GTFS flex service in the TDEI system.
     * @summary Updates a GTFS flex service in the TDEI system
     * @param {ServiceUpdate} body 
     * @param {string} orgId Owner organization id.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GTFSFlexServiceApi
     */
    public async updateService(body: ServiceUpdate, orgId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return GTFSFlexServiceApiFp(this.configuration).updateService(body, orgId, options).then((request) => request(this.axios, this.basePath));
    }
}
