/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Management API
 * Management API, describes admin & user activities in the TDEI system.
 *
 * OpenAPI spec version: v0.1
 * Contact: placeholder_support@transequity.cs.washington.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Response } from '../models';
import { Station } from '../models';
import { StationUpdate } from '../models';
/**
 * GTFSPathwaysStationApi - axios parameter creator
 * @export
 */
export const GTFSPathwaysStationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a GTFS Pathways station in the TDEI system. Returns the id for the newly created pathways station.
         * @summary Creates a GTFS Pathways station in the TDEI system
         * @param {Station} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createStation: async (body: Station, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createStation.');
            }
            const localVarPath = `/api/v1/station`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthorizationToken required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets the GTFS Pathways Station in the TDEI system .
         * @summary Gets the GTFS Pathways Station in the TDEI system 
         * @param {string} [tdei_station_id] Search by station Id.
         * @param {string} [searchText] Search by station name.
         * @param {string} [tdei_org_id] Owner organization id.
         * @param {Array<number>} [bbox] A bounding box which specifies the area to be searched. A bounding box is specified by a string providing the lat/lon coordinates of the corners of the bounding box. Coordinate should be specified as west, south, east, north.
         * @param {string} [page_no] Page number to fetch
         * @param {string} [page_size] Total records to fetch.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStation: async (tdei_station_id?: string, searchText?: string, tdei_org_id?: string, bbox?: Array<number>, page_no?: string, page_size?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/station`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthorizationToken required

            if (tdei_station_id !== undefined) {
                localVarQueryParameter['tdei_station_id'] = tdei_station_id;
            }

            if (searchText !== undefined) {
                localVarQueryParameter['searchText'] = searchText;
            }

            if (tdei_org_id !== undefined) {
                localVarQueryParameter['tdei_org_id'] = tdei_org_id;
            }

            if (bbox) {
                localVarQueryParameter['bbox'] = bbox;
            }

            if (page_no !== undefined) {
                localVarQueryParameter['page_no'] = page_no;
            }

            if (page_size !== undefined) {
                localVarQueryParameter['page_size'] = page_size;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Activates/Deactives the station.
         * @summary Activates/Deactives the station.
         * @param {string} orgId Owner organization id.
         * @param {string} stationId Station Id of the station to be Activated/Deactivated.
         * @param {boolean} status Boolean flag to Activate/Deactivate station.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setServiceStatus: async (orgId: string, stationId: string, status: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgId' is not null or undefined
            if (orgId === null || orgId === undefined) {
                throw new RequiredError('orgId','Required parameter orgId was null or undefined when calling setServiceStatus.');
            }
            // verify required parameter 'stationId' is not null or undefined
            if (stationId === null || stationId === undefined) {
                throw new RequiredError('stationId','Required parameter stationId was null or undefined when calling setServiceStatus.');
            }
            // verify required parameter 'status' is not null or undefined
            if (status === null || status === undefined) {
                throw new RequiredError('status','Required parameter status was null or undefined when calling setServiceStatus.');
            }
            const localVarPath = `/api/v1/station/{orgId}/{stationId}/active/{status}`
                .replace(`{${"orgId"}}`, encodeURIComponent(String(orgId)))
                .replace(`{${"stationId"}}`, encodeURIComponent(String(stationId)))
                .replace(`{${"status"}}`, encodeURIComponent(String(status)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthorizationToken required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates a GTFS Pathways station in the TDEI system.
         * @summary Updates a GTFS Pathways station in the TDEI system
         * @param {StationUpdate} body 
         * @param {string} orgId Owner organization id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStation: async (body: StationUpdate, orgId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateStation.');
            }
            // verify required parameter 'orgId' is not null or undefined
            if (orgId === null || orgId === undefined) {
                throw new RequiredError('orgId','Required parameter orgId was null or undefined when calling updateStation.');
            }
            const localVarPath = `/api/v1/station/{orgId}`
                .replace(`{${"orgId"}}`, encodeURIComponent(String(orgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthorizationToken required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GTFSPathwaysStationApi - functional programming interface
 * @export
 */
export const GTFSPathwaysStationApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Creates a GTFS Pathways station in the TDEI system. Returns the id for the newly created pathways station.
         * @summary Creates a GTFS Pathways station in the TDEI system
         * @param {Station} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createStation(body: Station, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Response>>> {
            const localVarAxiosArgs = await GTFSPathwaysStationApiAxiosParamCreator(configuration).createStation(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Gets the GTFS Pathways Station in the TDEI system .
         * @summary Gets the GTFS Pathways Station in the TDEI system 
         * @param {string} [tdei_station_id] Search by station Id.
         * @param {string} [searchText] Search by station name.
         * @param {string} [tdei_org_id] Owner organization id.
         * @param {Array<number>} [bbox] A bounding box which specifies the area to be searched. A bounding box is specified by a string providing the lat/lon coordinates of the corners of the bounding box. Coordinate should be specified as west, south, east, north.
         * @param {string} [page_no] Page number to fetch
         * @param {string} [page_size] Total records to fetch.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStation(tdei_station_id?: string, searchText?: string, tdei_org_id?: string, bbox?: Array<number>, page_no?: string, page_size?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Station>>> {
            const localVarAxiosArgs = await GTFSPathwaysStationApiAxiosParamCreator(configuration).getStation(tdei_station_id, searchText, tdei_org_id, bbox, page_no, page_size, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Activates/Deactives the station.
         * @summary Activates/Deactives the station.
         * @param {string} orgId Owner organization id.
         * @param {string} stationId Station Id of the station to be Activated/Deactivated.
         * @param {boolean} status Boolean flag to Activate/Deactivate station.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setServiceStatus(orgId: string, stationId: string, status: boolean, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await GTFSPathwaysStationApiAxiosParamCreator(configuration).setServiceStatus(orgId, stationId, status, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Updates a GTFS Pathways station in the TDEI system.
         * @summary Updates a GTFS Pathways station in the TDEI system
         * @param {StationUpdate} body 
         * @param {string} orgId Owner organization id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateStation(body: StationUpdate, orgId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await GTFSPathwaysStationApiAxiosParamCreator(configuration).updateStation(body, orgId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * GTFSPathwaysStationApi - factory interface
 * @export
 */
export const GTFSPathwaysStationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Creates a GTFS Pathways station in the TDEI system. Returns the id for the newly created pathways station.
         * @summary Creates a GTFS Pathways station in the TDEI system
         * @param {Station} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createStation(body: Station, options?: AxiosRequestConfig): Promise<AxiosResponse<Response>> {
            return GTFSPathwaysStationApiFp(configuration).createStation(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets the GTFS Pathways Station in the TDEI system .
         * @summary Gets the GTFS Pathways Station in the TDEI system 
         * @param {string} [tdei_station_id] Search by station Id.
         * @param {string} [searchText] Search by station name.
         * @param {string} [tdei_org_id] Owner organization id.
         * @param {Array<number>} [bbox] A bounding box which specifies the area to be searched. A bounding box is specified by a string providing the lat/lon coordinates of the corners of the bounding box. Coordinate should be specified as west, south, east, north.
         * @param {string} [page_no] Page number to fetch
         * @param {string} [page_size] Total records to fetch.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStation(tdei_station_id?: string, searchText?: string, tdei_org_id?: string, bbox?: Array<number>, page_no?: string, page_size?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Station>> {
            return GTFSPathwaysStationApiFp(configuration).getStation(tdei_station_id, searchText, tdei_org_id, bbox, page_no, page_size, options).then((request) => request(axios, basePath));
        },
        /**
         * Activates/Deactives the station.
         * @summary Activates/Deactives the station.
         * @param {string} orgId Owner organization id.
         * @param {string} stationId Station Id of the station to be Activated/Deactivated.
         * @param {boolean} status Boolean flag to Activate/Deactivate station.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setServiceStatus(orgId: string, stationId: string, status: boolean, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return GTFSPathwaysStationApiFp(configuration).setServiceStatus(orgId, stationId, status, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates a GTFS Pathways station in the TDEI system.
         * @summary Updates a GTFS Pathways station in the TDEI system
         * @param {StationUpdate} body 
         * @param {string} orgId Owner organization id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateStation(body: StationUpdate, orgId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return GTFSPathwaysStationApiFp(configuration).updateStation(body, orgId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GTFSPathwaysStationApi - object-oriented interface
 * @export
 * @class GTFSPathwaysStationApi
 * @extends {BaseAPI}
 */
export class GTFSPathwaysStationApi extends BaseAPI {
    /**
     * Creates a GTFS Pathways station in the TDEI system. Returns the id for the newly created pathways station.
     * @summary Creates a GTFS Pathways station in the TDEI system
     * @param {Station} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GTFSPathwaysStationApi
     */
    public async createStation(body: Station, options?: AxiosRequestConfig) : Promise<AxiosResponse<Response>> {
        return GTFSPathwaysStationApiFp(this.configuration).createStation(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Gets the GTFS Pathways Station in the TDEI system .
     * @summary Gets the GTFS Pathways Station in the TDEI system 
     * @param {string} [tdei_station_id] Search by station Id.
     * @param {string} [searchText] Search by station name.
     * @param {string} [tdei_org_id] Owner organization id.
     * @param {Array<number>} [bbox] A bounding box which specifies the area to be searched. A bounding box is specified by a string providing the lat/lon coordinates of the corners of the bounding box. Coordinate should be specified as west, south, east, north.
     * @param {string} [page_no] Page number to fetch
     * @param {string} [page_size] Total records to fetch.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GTFSPathwaysStationApi
     */
    public async getStation(tdei_station_id?: string, searchText?: string, tdei_org_id?: string, bbox?: Array<number>, page_no?: string, page_size?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Station>> {
        return GTFSPathwaysStationApiFp(this.configuration).getStation(tdei_station_id, searchText, tdei_org_id, bbox, page_no, page_size, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Activates/Deactives the station.
     * @summary Activates/Deactives the station.
     * @param {string} orgId Owner organization id.
     * @param {string} stationId Station Id of the station to be Activated/Deactivated.
     * @param {boolean} status Boolean flag to Activate/Deactivate station.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GTFSPathwaysStationApi
     */
    public async setServiceStatus(orgId: string, stationId: string, status: boolean, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return GTFSPathwaysStationApiFp(this.configuration).setServiceStatus(orgId, stationId, status, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Updates a GTFS Pathways station in the TDEI system.
     * @summary Updates a GTFS Pathways station in the TDEI system
     * @param {StationUpdate} body 
     * @param {string} orgId Owner organization id.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GTFSPathwaysStationApi
     */
    public async updateStation(body: StationUpdate, orgId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return GTFSPathwaysStationApiFp(this.configuration).updateStation(body, orgId, options).then((request) => request(this.axios, this.basePath));
    }
}
