/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Management API
 * Management API, describes admin & user activities in the TDEI system.
 *
 * OpenAPI spec version: v0.1
 * Contact: placeholder_support@transequity.cs.washington.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ProjectGroup } from '../models';
import { ProjectGroupList } from '../models';
import { ProjectGroupUser } from '../models';
import { Response } from '../models';
/**
 * ProjectGroupApi - axios parameter creator
 * @export
 */
export const ProjectGroupApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates an project group in the TDEI system.  Returns the id for the newly created project group.
         * @summary Creates an project group in the TDEI system 
         * @param {ProjectGroup} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProjectGroup: async (body: ProjectGroup, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createProjectGroup.');
            }
            const localVarPath = `/api/v1/project-group`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthorizationToken required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Activates/Deactives the project group.
         * @summary Activates/Deactives the project group.
         * @param {string} projectGroupId projectGroupId of the project group to be Activated/Deactivated.
         * @param {boolean} status Boolean flag to Activate/Deactivate project group.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProjectGroup: async (projectGroupId: string, status: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectGroupId' is not null or undefined
            if (projectGroupId === null || projectGroupId === undefined) {
                throw new RequiredError('projectGroupId','Required parameter projectGroupId was null or undefined when calling deleteProjectGroup.');
            }
            // verify required parameter 'status' is not null or undefined
            if (status === null || status === undefined) {
                throw new RequiredError('status','Required parameter status was null or undefined when calling deleteProjectGroup.');
            }
            const localVarPath = `/api/v1/project-group/{projectGroupId}/active/{status}`
                .replace(`{${"projectGroupId"}}`, encodeURIComponent(String(projectGroupId)))
                .replace(`{${"status"}}`, encodeURIComponent(String(status)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthorizationToken required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets the project groups in the TDEI system.
         * @summary Gets the project groups in the TDEI system 
         * @param {string} [tdei_project_group_id] Search by project group Id.
         * @param {string} [searchText] Search by project group name.
         * @param {Array<number>} [bbox] A bounding box which specifies the area to be searched. A bounding box is specified by a string providing the lat/lon coordinates of the corners of the bounding box. Coordinate should be specified as west, south, east, north.
         * @param {string} [page_no] Page number to fetch
         * @param {string} [page_size] Total records to fetch.
         * @param {boolean} [show_inactive] Show inactive project groups
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectGroup: async (tdei_project_group_id?: string, searchText?: string, bbox?: Array<number>, page_no?: string, page_size?: string, show_inactive?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/project-group`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthorizationToken required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (tdei_project_group_id !== undefined) {
                localVarQueryParameter['tdei_project_group_id'] = tdei_project_group_id;
            }

            if (searchText !== undefined) {
                localVarQueryParameter['searchText'] = searchText;
            }

            if (bbox) {
                localVarQueryParameter['bbox'] = bbox;
            }

            if (page_no !== undefined) {
                localVarQueryParameter['page_no'] = page_no;
            }

            if (page_size !== undefined) {
                localVarQueryParameter['page_size'] = page_size;
            }

            if (show_inactive !== undefined) {
                localVarQueryParameter['show_inactive'] = show_inactive;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets the project group users in the TDEI system.
         * @summary Gets the project group users in the TDEI system 
         * @param {string} projectGroupId Project group id for which users to be fetched
         * @param {string} [searchText] Search by first_name, last_name or username.
         * @param {string} [page_no] Page number to fetch
         * @param {string} [page_size] Total records to fetch.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectGroupUsers: async (projectGroupId: string, searchText?: string, page_no?: string, page_size?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectGroupId' is not null or undefined
            if (projectGroupId === null || projectGroupId === undefined) {
                throw new RequiredError('projectGroupId','Required parameter projectGroupId was null or undefined when calling getProjectGroupUsers.');
            }
            const localVarPath = `/api/v1/project-group/{projectGroupId}/users`
                .replace(`{${"projectGroupId"}}`, encodeURIComponent(String(projectGroupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthorizationToken required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (searchText !== undefined) {
                localVarQueryParameter['searchText'] = searchText;
            }

            if (page_no !== undefined) {
                localVarQueryParameter['page_no'] = page_no;
            }

            if (page_size !== undefined) {
                localVarQueryParameter['page_size'] = page_size;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates an project group in the TDEI system.  Returns success if updated.
         * @summary Updates an project group in the TDEI system 
         * @param {ProjectGroup} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProjectGroup: async (body: ProjectGroup, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateProjectGroup.');
            }
            const localVarPath = `/api/v1/project-group`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthorizationToken required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProjectGroupApi - functional programming interface
 * @export
 */
export const ProjectGroupApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Creates an project group in the TDEI system.  Returns the id for the newly created project group.
         * @summary Creates an project group in the TDEI system 
         * @param {ProjectGroup} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createProjectGroup(body: ProjectGroup, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Response>>> {
            const localVarAxiosArgs = await ProjectGroupApiAxiosParamCreator(configuration).createProjectGroup(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Activates/Deactives the project group.
         * @summary Activates/Deactives the project group.
         * @param {string} projectGroupId projectGroupId of the project group to be Activated/Deactivated.
         * @param {boolean} status Boolean flag to Activate/Deactivate project group.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteProjectGroup(projectGroupId: string, status: boolean, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await ProjectGroupApiAxiosParamCreator(configuration).deleteProjectGroup(projectGroupId, status, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Gets the project groups in the TDEI system.
         * @summary Gets the project groups in the TDEI system 
         * @param {string} [tdei_project_group_id] Search by project group Id.
         * @param {string} [searchText] Search by project group name.
         * @param {Array<number>} [bbox] A bounding box which specifies the area to be searched. A bounding box is specified by a string providing the lat/lon coordinates of the corners of the bounding box. Coordinate should be specified as west, south, east, north.
         * @param {string} [page_no] Page number to fetch
         * @param {string} [page_size] Total records to fetch.
         * @param {boolean} [show_inactive] Show inactive project groups
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectGroup(tdei_project_group_id?: string, searchText?: string, bbox?: Array<number>, page_no?: string, page_size?: string, show_inactive?: boolean, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<ProjectGroupList>>>> {
            const localVarAxiosArgs = await ProjectGroupApiAxiosParamCreator(configuration).getProjectGroup(tdei_project_group_id, searchText, bbox, page_no, page_size, show_inactive, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Gets the project group users in the TDEI system.
         * @summary Gets the project group users in the TDEI system 
         * @param {string} projectGroupId Project group id for which users to be fetched
         * @param {string} [searchText] Search by first_name, last_name or username.
         * @param {string} [page_no] Page number to fetch
         * @param {string} [page_size] Total records to fetch.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectGroupUsers(projectGroupId: string, searchText?: string, page_no?: string, page_size?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<ProjectGroupUser>>>> {
            const localVarAxiosArgs = await ProjectGroupApiAxiosParamCreator(configuration).getProjectGroupUsers(projectGroupId, searchText, page_no, page_size, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Updates an project group in the TDEI system.  Returns success if updated.
         * @summary Updates an project group in the TDEI system 
         * @param {ProjectGroup} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProjectGroup(body: ProjectGroup, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await ProjectGroupApiAxiosParamCreator(configuration).updateProjectGroup(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ProjectGroupApi - factory interface
 * @export
 */
export const ProjectGroupApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Creates an project group in the TDEI system.  Returns the id for the newly created project group.
         * @summary Creates an project group in the TDEI system 
         * @param {ProjectGroup} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createProjectGroup(body: ProjectGroup, options?: AxiosRequestConfig): Promise<AxiosResponse<Response>> {
            return ProjectGroupApiFp(configuration).createProjectGroup(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Activates/Deactives the project group.
         * @summary Activates/Deactives the project group.
         * @param {string} projectGroupId projectGroupId of the project group to be Activated/Deactivated.
         * @param {boolean} status Boolean flag to Activate/Deactivate project group.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteProjectGroup(projectGroupId: string, status: boolean, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return ProjectGroupApiFp(configuration).deleteProjectGroup(projectGroupId, status, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets the project groups in the TDEI system.
         * @summary Gets the project groups in the TDEI system 
         * @param {string} [tdei_project_group_id] Search by project group Id.
         * @param {string} [searchText] Search by project group name.
         * @param {Array<number>} [bbox] A bounding box which specifies the area to be searched. A bounding box is specified by a string providing the lat/lon coordinates of the corners of the bounding box. Coordinate should be specified as west, south, east, north.
         * @param {string} [page_no] Page number to fetch
         * @param {string} [page_size] Total records to fetch.
         * @param {boolean} [show_inactive] Show inactive project groups
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectGroup(tdei_project_group_id?: string, searchText?: string, bbox?: Array<number>, page_no?: string, page_size?: string, show_inactive?: boolean, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<ProjectGroupList>>> {
            return ProjectGroupApiFp(configuration).getProjectGroup(tdei_project_group_id, searchText, bbox, page_no, page_size, show_inactive, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets the project group users in the TDEI system.
         * @summary Gets the project group users in the TDEI system 
         * @param {string} projectGroupId Project group id for which users to be fetched
         * @param {string} [searchText] Search by first_name, last_name or username.
         * @param {string} [page_no] Page number to fetch
         * @param {string} [page_size] Total records to fetch.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectGroupUsers(projectGroupId: string, searchText?: string, page_no?: string, page_size?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<ProjectGroupUser>>> {
            return ProjectGroupApiFp(configuration).getProjectGroupUsers(projectGroupId, searchText, page_no, page_size, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates an project group in the TDEI system.  Returns success if updated.
         * @summary Updates an project group in the TDEI system 
         * @param {ProjectGroup} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProjectGroup(body: ProjectGroup, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return ProjectGroupApiFp(configuration).updateProjectGroup(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProjectGroupApi - object-oriented interface
 * @export
 * @class ProjectGroupApi
 * @extends {BaseAPI}
 */
export class ProjectGroupApi extends BaseAPI {
    /**
     * Creates an project group in the TDEI system.  Returns the id for the newly created project group.
     * @summary Creates an project group in the TDEI system 
     * @param {ProjectGroup} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectGroupApi
     */
    public async createProjectGroup(body: ProjectGroup, options?: AxiosRequestConfig) : Promise<AxiosResponse<Response>> {
        return ProjectGroupApiFp(this.configuration).createProjectGroup(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Activates/Deactives the project group.
     * @summary Activates/Deactives the project group.
     * @param {string} projectGroupId projectGroupId of the project group to be Activated/Deactivated.
     * @param {boolean} status Boolean flag to Activate/Deactivate project group.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectGroupApi
     */
    public async deleteProjectGroup(projectGroupId: string, status: boolean, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return ProjectGroupApiFp(this.configuration).deleteProjectGroup(projectGroupId, status, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Gets the project groups in the TDEI system.
     * @summary Gets the project groups in the TDEI system 
     * @param {string} [tdei_project_group_id] Search by project group Id.
     * @param {string} [searchText] Search by project group name.
     * @param {Array<number>} [bbox] A bounding box which specifies the area to be searched. A bounding box is specified by a string providing the lat/lon coordinates of the corners of the bounding box. Coordinate should be specified as west, south, east, north.
     * @param {string} [page_no] Page number to fetch
     * @param {string} [page_size] Total records to fetch.
     * @param {boolean} [show_inactive] Show inactive project groups
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectGroupApi
     */
    public async getProjectGroup(tdei_project_group_id?: string, searchText?: string, bbox?: Array<number>, page_no?: string, page_size?: string, show_inactive?: boolean, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<ProjectGroupList>>> {
        return ProjectGroupApiFp(this.configuration).getProjectGroup(tdei_project_group_id, searchText, bbox, page_no, page_size, show_inactive, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Gets the project group users in the TDEI system.
     * @summary Gets the project group users in the TDEI system 
     * @param {string} projectGroupId Project group id for which users to be fetched
     * @param {string} [searchText] Search by first_name, last_name or username.
     * @param {string} [page_no] Page number to fetch
     * @param {string} [page_size] Total records to fetch.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectGroupApi
     */
    public async getProjectGroupUsers(projectGroupId: string, searchText?: string, page_no?: string, page_size?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<ProjectGroupUser>>> {
        return ProjectGroupApiFp(this.configuration).getProjectGroupUsers(projectGroupId, searchText, page_no, page_size, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Updates an project group in the TDEI system.  Returns success if updated.
     * @summary Updates an project group in the TDEI system 
     * @param {ProjectGroup} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectGroupApi
     */
    public async updateProjectGroup(body: ProjectGroup, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return ProjectGroupApiFp(this.configuration).updateProjectGroup(body, options).then((request) => request(this.axios, this.basePath));
    }
}
