/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Management API
 * Management API, describes admin & user activities in the TDEI system.
 *
 * OpenAPI spec version: v0.1
 * Contact: placeholder_support@transequity.cs.washington.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeoJSONPolygon } from './geo-jsonpolygon';
/**
 * 
 * @export
 * @interface GeoJSONFeature
 */
export interface GeoJSONFeature {
    /**
     * 
     * @type {string}
     * @memberof GeoJSONFeature
     */
    type: GeoJSONFeatureTypeEnum;
    /**
     * 
     * @type {number | string}
     * @memberof GeoJSONFeature
     */
    id?: number | string;
    /**
     * 
     * @type {any}
     * @memberof GeoJSONFeature
     */
    properties: any;
    /**
     * 
     * @type {GeoJSONPolygon}
     * @memberof GeoJSONFeature
     */
    geometry: GeoJSONPolygon;
}

/**
    * @export
    * @enum {string}
    */
export enum GeoJSONFeatureTypeEnum {
    Feature = 'Feature'
}

