/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Management API
 * Management API, describes admin & user activities in the TDEI system.
 *
 * OpenAPI spec version: v0.1
 * Contact: placeholder_support@transequity.cs.washington.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeoJSONFeature } from './geo-jsonfeature';
/**
 * 
 * @export
 * @interface Polygon
 */
export interface Polygon {
    /**
     * 
     * @type {string}
     * @memberof Polygon
     */
    type: PolygonTypeEnum;
    /**
     * 
     * @type {Array<GeoJSONFeature>}
     * @memberof Polygon
     */
    features: Array<GeoJSONFeature>;
}

/**
    * @export
    * @enum {string}
    */
export enum PolygonTypeEnum {
    FeatureCollection = 'FeatureCollection'
}

