/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Management API
 * Management API, describes admin & user activities in the TDEI system.
 *
 * OpenAPI spec version: v0.1
 * Contact: placeholder_support@transequity.cs.washington.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * User associated project groups and roles.
 * @export
 * @interface ProjectGroupRoles
 */
export interface ProjectGroupRoles {
    /**
     * 
     * @type {string}
     * @memberof ProjectGroupRoles
     */
    tdei_project_group_id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectGroupRoles
     */
    project_group_name?: string;
    /**
     * List of roles associated with project group.
     * @type {Array<string>}
     * @memberof ProjectGroupRoles
     */
    roles?: Array<string>;
}
