/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Management API
 * Management API, describes admin & user activities in the TDEI system.
 *
 * OpenAPI spec version: v0.1
 * Contact: placeholder_support@transequity.cs.washington.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProjectGroupUser
 */
export interface ProjectGroupUser {
    /**
     * 
     * @type {string}
     * @memberof ProjectGroupUser
     */
    user_id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectGroupUser
     */
    first_name: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectGroupUser
     */
    last_name: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectGroupUser
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectGroupUser
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectGroupUser
     */
    phone: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectGroupUser
     */
    roles: Array<string>;
}
