/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Management API
 * Management API, describes admin & user activities in the TDEI system.
 *
 * OpenAPI spec version: v0.1
 * Contact: placeholder_support@transequity.cs.washington.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Polygon } from './polygon';
/**
 * Describes a gtfs pathways station.
 * @export
 * @interface Station
 */
export interface Station {
    /**
     * Station Id uniquely represented in the TDEI system. System generated.
     * @type {string}
     * @memberof Station
     */
    tdei_station_id?: string;
    /**
     * Project group id of the station.
     * @type {string}
     * @memberof Station
     */
    tdei_project_group_id: string;
    /**
     * Name of the location. The ame should match the agency's rider-facing name for the location as printed on a timetable, published online, or represented on signage.
     * @type {string}
     * @memberof Station
     */
    station_name: string;
    /**
     * 
     * @type {Polygon}
     * @memberof Station
     */
    polygon?: Polygon;
}
