/* tslint:disable */
/* eslint-disable */
/**
 * TDEI Management API
 * Management API, describes admin & user activities in the TDEI system.
 *
 * OpenAPI spec version: v0.1
 * Contact: placeholder_support@transequity.cs.washington.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Describes a user registration details.
 * @export
 * @interface User
 */
export interface User {
    /**
     * User Id name of the user.
     * @type {string}
     * @memberof User
     */
    id?: string;
    /**
     * First name of the user.
     * @type {string}
     * @memberof User
     */
    firstName?: string;
    /**
     * Last name of the user.
     * @type {string}
     * @memberof User
     */
    lastName?: string;
    /**
     * Email address of the user for communication.
     * @type {string}
     * @memberof User
     */
    email?: string;
    /**
     * Phone of the user for communication.
     * @type {string}
     * @memberof User
     */
    phone?: string;
}
